//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karabina.SharePoint.Provisioning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karabina.SharePoint.Provisioning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a provisioning template for edit and saving the changes.
        /// </summary>
        internal static string Edit00 {
            get {
                return ResourceManager.GetString("Edit00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provisioning template file name being edited will appear here.
        /// </summary>
        internal static string Edit01 {
            get {
                return ResourceManager.GetString("Edit01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the provisioning template to edit.
        /// </summary>
        internal static string Edit02 {
            get {
                return ResourceManager.GetString("Edit02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to save the changes made to the provisioning template.
        /// </summary>
        internal static string Edit03 {
            get {
                return ResourceManager.GetString("Edit03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierachical display of the provisioning template items. Click a node to edit it, right click for edit options.
        /// </summary>
        internal static string Edit04 {
            get {
                return ResourceManager.GetString("Edit04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the regional settings of the provisioning template.
        /// </summary>
        internal static string Edit05 {
            get {
                return ResourceManager.GetString("Edit05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected node child items. Double click to view the item, right click for edit options.
        /// </summary>
        internal static string Edit06 {
            get {
                return ResourceManager.GetString("Edit06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahh, you found the lost edit tag.
        /// </summary>
        internal static string Edit07 {
            get {
                return ResourceManager.GetString("Edit07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the composed look settings of the provisioning template.
        /// </summary>
        internal static string Edit08 {
            get {
                return ResourceManager.GetString("Edit08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the web settings of the provisioning template.
        /// </summary>
        internal static string Edit09 {
            get {
                return ResourceManager.GetString("Edit09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change properties of the provisioning template. Double click to change selected item, right click for edit options.
        /// </summary>
        internal static string Edit10 {
            get {
                return ResourceManager.GetString("Edit10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the details of the selected provisioning template item. Right click for edit options. On save empty items will be deleted.
        /// </summary>
        internal static string Edit11 {
            get {
                return ResourceManager.GetString("Edit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExitApplicationRed {
            get {
                object obj = ResourceManager.GetObject("ExitApplicationRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karabina122x122 {
            get {
                object obj = ResourceManager.GetObject("Karabina122x122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karabina16x16 {
            get {
                object obj = ResourceManager.GetObject("Karabina16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karabina32x32 {
            get {
                object obj = ResourceManager.GetObject("Karabina32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karabina48x48 {
            get {
                object obj = ResourceManager.GetObject("Karabina48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KarabinaWorkflowFeatureIcon_Generic {
            get {
                object obj = ResourceManager.GetObject("KarabinaWorkflowFeatureIcon_Generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the mouse over the items to see the explanation of the option.
        /// </summary>
        internal static string Option00 {
            get {
                return ResourceManager.GetString("Option00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents regional settings that are used on the server that is running SharePoint Server..
        /// </summary>
        internal static string Option01 {
            get {
                return ResourceManager.GetString("Option01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the language code identifiers (LCIDs) of the languages that are enabled for the site..
        /// </summary>
        internal static string Option02 {
            get {
                return ResourceManager.GetString("Option02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit settings.
        /// </summary>
        internal static string Option03 {
            get {
                return ResourceManager.GetString("Option03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the site policy that currently is applied. Apply a policy to a site..
        /// </summary>
        internal static string Option04 {
            get {
                return ResourceManager.GetString("Option04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply various site security settings.
        /// </summary>
        internal static string Option05 {
            get {
                return ResourceManager.GetString("Option05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a collection of Field objects as defined for the site..
        /// </summary>
        internal static string Option06 {
            get {
                return ResourceManager.GetString("Option06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a collection of Web site content types..
        /// </summary>
        internal static string Option07 {
            get {
                return ResourceManager.GetString("Option07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the collection of all lists that are contained in the web site excluding content.
        /// </summary>
        internal static string Option08 {
            get {
                return ResourceManager.GetString("Option08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a collection of custom actions associated with a SharePoint list, Web site, or subsite..
        /// </summary>
        internal static string Option09 {
            get {
                return ResourceManager.GetString("Option09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a collection of activated features at the site and web..
        /// </summary>
        internal static string Option10 {
            get {
                return ResourceManager.GetString("Option10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the current composed look settings..
        /// </summary>
        internal static string Option11 {
            get {
                return ResourceManager.GetString("Option11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the default page for the site or web..
        /// </summary>
        internal static string Option12 {
            get {
                return ResourceManager.GetString("Option12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a collection of metadata for the Web site..
        /// </summary>
        internal static string Option13 {
            get {
                return ResourceManager.GetString("Option13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the master page and page layouts if the publishing feature is activated.
        /// </summary>
        internal static string Option14 {
            get {
                return ResourceManager.GetString("Option14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply all workflow definitions and subscriptions.
        /// </summary>
        internal static string Option15 {
            get {
                return ResourceManager.GetString("Option15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the master page url, default page url, logo url and css files urls..
        /// </summary>
        internal static string Option16 {
            get {
                return ResourceManager.GetString("Option16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply navigation settings if the publishing feature is activated.
        /// </summary>
        internal static string Option17 {
            get {
                return ResourceManager.GetString("Option17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all settings from the template that are in the base template.
        /// </summary>
        internal static string Option18 {
            get {
                return ResourceManager.GetString("Option18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include composed look files (theme files, site logo, alternate css).
        /// </summary>
        internal static string Option19 {
            get {
                return ResourceManager.GetString("Option19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether to persist publishing files (MasterPages and PageLayouts).
        /// </summary>
        internal static string Option20 {
            get {
                return ResourceManager.GetString("Option20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will create resource files named &quot;PnP_Resource_[LCID].resx for every supported language..
        /// </summary>
        internal static string Option21 {
            get {
                return ResourceManager.GetString("Option21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether to extract native publishing files (MasterPages and PageLayouts).
        /// </summary>
        internal static string Option22 {
            get {
                return ResourceManager.GetString("Option22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply all term groups and term sets.
        /// </summary>
        internal static string Option23 {
            get {
                return ResourceManager.GetString("Option23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the term group and term sets defined for the site.
        /// </summary>
        internal static string Option24 {
            get {
                return ResourceManager.GetString("Option24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the term group security.
        /// </summary>
        internal static string Option25 {
            get {
                return ResourceManager.GetString("Option25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the site securty groups (owners, members &amp; visitors).
        /// </summary>
        internal static string Option26 {
            get {
                return ResourceManager.GetString("Option26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports search configuration settings at the web and site collection level in XML format..
        /// </summary>
        internal static string Option27 {
            get {
                return ResourceManager.GetString("Option27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include / apply the content of lists and libraries.
        /// </summary>
        internal static string Option28 {
            get {
                return ResourceManager.GetString("Option28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details about the current operation will appear on this form.
        /// </summary>
        internal static string Progress00 {
            get {
                return ResourceManager.GetString("Progress00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current operation details will appear on this listbox.
        /// </summary>
        internal static string Progress01 {
            get {
                return ResourceManager.GetString("Progress01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to close this progress form.
        /// </summary>
        internal static string Progress02 {
            get {
                return ResourceManager.GetString("Progress02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the fields to create a provisioning template from a SharePoint site.
        /// </summary>
        internal static string Source00 {
            get {
                return ResourceManager.GetString("Source00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the URL of the SharePoint site to save in the provisioning template.
        /// </summary>
        internal static string Source01 {
            get {
                return ResourceManager.GetString("Source01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Premises - On the SharePoint server check this option if logged in with the farm account.
        /// </summary>
        internal static string Source02 {
            get {
                return ResourceManager.GetString("Source02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online - Specify email address; On Premises - Specify domain\account.
        /// </summary>
        internal static string Source03 {
            get {
                return ResourceManager.GetString("Source03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the password for the account.
        /// </summary>
        internal static string Source04 {
            get {
                return ResourceManager.GetString("Source04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioning template file name will appear here.
        /// </summary>
        internal static string Source05 {
            get {
                return ResourceManager.GetString("Source05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to specify the provisioning template file.
        /// </summary>
        internal static string Source06 {
            get {
                return ResourceManager.GetString("Source06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to specify what should be included in the provisioning template.
        /// </summary>
        internal static string Source07 {
            get {
                return ResourceManager.GetString("Source07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create the provisioning file, the progress form will appear.
        /// </summary>
        internal static string Source08 {
            get {
                return ResourceManager.GetString("Source08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Provisioning Tool - Front end for Office Dev PnP Core library for SharePoint.
        /// </summary>
        internal static string String00 {
            get {
                return ResourceManager.GetString("String00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the Create Template form.
        /// </summary>
        internal static string String01 {
            get {
                return ResourceManager.GetString("String01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the Edit Template form.
        /// </summary>
        internal static string String02 {
            get {
                return ResourceManager.GetString("String02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the Apply Template form.
        /// </summary>
        internal static string String03 {
            get {
                return ResourceManager.GetString("String03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to exit this application.
        /// </summary>
        internal static string String04 {
            get {
                return ResourceManager.GetString("String04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cascade the open forms.
        /// </summary>
        internal static string String05 {
            get {
                return ResourceManager.GetString("String05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to tile the open forms vertically.
        /// </summary>
        internal static string String06 {
            get {
                return ResourceManager.GetString("String06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to tile the open forms horizontally.
        /// </summary>
        internal static string String07 {
            get {
                return ResourceManager.GetString("String07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the arrange forms commands.
        /// </summary>
        internal static string String08 {
            get {
                return ResourceManager.GetString("String08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the template commands.
        /// </summary>
        internal static string String09 {
            get {
                return ResourceManager.GetString("String09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the fields to apply a provisioning template to a SharePoint site.
        /// </summary>
        internal static string Target00 {
            get {
                return ResourceManager.GetString("Target00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected provisioning template file name will appear here.
        /// </summary>
        internal static string Target01 {
            get {
                return ResourceManager.GetString("Target01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the provisioning template file.
        /// </summary>
        internal static string Target02 {
            get {
                return ResourceManager.GetString("Target02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the URL of the SharePoint site to apply the provisioning template.
        /// </summary>
        internal static string Target03 {
            get {
                return ResourceManager.GetString("Target03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Premises - On the SharePoint server check this option if logged in with the farm account.
        /// </summary>
        internal static string Target04 {
            get {
                return ResourceManager.GetString("Target04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online - Specify email address; On Premises - Specify domain\account.
        /// </summary>
        internal static string Target05 {
            get {
                return ResourceManager.GetString("Target05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the password for the account.
        /// </summary>
        internal static string Target06 {
            get {
                return ResourceManager.GetString("Target06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to specify what should be applied from the provisioning template.
        /// </summary>
        internal static string Target07 {
            get {
                return ResourceManager.GetString("Target07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to apply the provisioning template to the SharePoint site.
        /// </summary>
        internal static string Target08 {
            get {
                return ResourceManager.GetString("Target08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TemplateApplyRed {
            get {
                object obj = ResourceManager.GetObject("TemplateApplyRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TemplateCreateRed {
            get {
                object obj = ResourceManager.GetObject("TemplateCreateRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TemplateEditRed {
            get {
                object obj = ResourceManager.GetObject("TemplateEditRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the SharePoint version to perform the action on.
        /// </summary>
        internal static string Version00 {
            get {
                return ResourceManager.GetString("Version00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SharePoint 2013 On Premises to perform the action on.
        /// </summary>
        internal static string Version01 {
            get {
                return ResourceManager.GetString("Version01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SharePoint 2016 On Premises to perform the action on.
        /// </summary>
        internal static string Version02 {
            get {
                return ResourceManager.GetString("Version02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SharePoint 2016 Online to perform the action on.
        /// </summary>
        internal static string Version03 {
            get {
                return ResourceManager.GetString("Version03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to make the selection.
        /// </summary>
        internal static string Version04 {
            get {
                return ResourceManager.GetString("Version04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cancel the action.
        /// </summary>
        internal static string Version05 {
            get {
                return ResourceManager.GetString("Version05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewCascadeNew {
            get {
                object obj = ResourceManager.GetObject("ViewCascadeNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewHorizontalNew {
            get {
                object obj = ResourceManager.GetObject("ViewHorizontalNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewVerticalNew {
            get {
                object obj = ResourceManager.GetObject("ViewVerticalNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
